### PR TITLE
Remove ACL tags from BM

### PR DESCRIPTION
**Pull request by marian-pritsak**

### CODE REVIEW

**Comment by marian-pritsak** [comment]
This is a manual revert of https://github.com/sonic-net/DASH/pull/336

**Comment by marian-pritsak** [comment]
@prsunny @KrisNey-MSFT Can you take a look?

**Comment by KrisNey-MSFT** [comment]
LGTM, will wait to hear from @prsunny

**Review by chrispsommers — APPROVED** [review]
LGTM

**Review by kperumalbfn — APPROVED** [review]

**Comment by KrisNey-MSFT** [comment]
[like]  Kristina Moore reacted to your message:
________________________________

**Comment by KrisNey-MSFT** [comment]
3 ppl reviewed, merging

**Comment by KrisNey-MSFT** [comment]
@marian-pritsak and @prsunny - the ACL tagging is removed from P4 code.  Do we also want to remove it from the SONiC DASH HLD **documentation**?  Or leave it there, in case some suppliers would want the information?   We had mentioned removing it from docs in Issue421

[Removal of P4 for ACL Tags](https://github.com/sonic-net/DASH/issues/421)

**Comment by prsunny** [comment]
> @marian-pritsak and @prsunny - the ACL tagging is removed from P4 code. Do we also want to remove it from the SONiC DASH HLD **documentation**? Or leave it there, in case some suppliers would want the information? We had mentioned removing it from docs in Issue421
> 
> [Removal of P4 for ACL Tags](https://github.com/sonic-net/DASH/issues/421)

I suggest leave it there.

**Pull request merged**
