### PR TITLE
Correct syntax errors in PNA_CONNTRACK version of code

### PR DESCRIPTION
**Pull request by jfingerh**

### CODE REVIEW

**Comment by jfingerh** [comment]
When one #define's the preprocessor symbol PNA_CONNTRACK, parts of the code enabled have syntax and semantic errors. These changes correct those errors.

**Comment by chrispsommers** [comment]
Hi @jfingerh can the code be compiled with the existing toolchain and suitable macro flag, and if so, I'd propose we make a CI pipeline to test it with every build. I can help.

**Comment by KrisNey-MSFT** [comment]
If/when we have a BE, this will be ok

**Review by chrispsommers — APPROVED** [review]
LGTM, thanks

**Pull request merged**
