### PR TITLE
[submodule] Update SAI submodule to origin/master

### PR DESCRIPTION
**Pull request by kcudnik**
To include
[test] Refactor saithriftv2 Makefile
https://github.com/opencomputeproject/SAI/commit/4f39bd

### CODE REVIEW

**Comment by kcudnik** [comment]
@chrispsommers please review and if good to go please merge

**Review by chrispsommers — APPROVED** [review]
LGTM, thanks!

**Comment by chrispsommers** [comment]
@kcudnik Does this pave the way to resolve https://github.com/sonic-net/DASH/issues/395 ? In particular, does sai-thrift still require sai meta code inside vendor libsai?

**Comment by kcudnik** [comment]
> @kcudnik Does this pave the way to resolve #395 ? In particular, does sai-thrift still require sai meta code inside vendor libsai?

No, currently saimetadata*.o objects are compiled into libsai.so (from dash)

for example: in ~/SAI/test/saithriftv2/Makefile you can se saimetadata lib added when saivs is compiled
```make
 40 ifeq ($(platform),vs)
 41 LIBS = -lthrift -lpthread -lsaivs -lsaimeta -lsaimetadata -lzmq
 42 else
 43 LIBS = -lthrift -lpthread -lsai
 44 endif
```

so currently that libsai.so from DASH trhift will require that metadata, i have PR almost ready that will simplify this, Makefile DASH/dash-pipeline/SAI/templates/Makefile.j2, and metadata function sai_metadata_get_attr_metadata is required from SAI/meta/sai_rpc_frontend.cpp, since they need to get a attribute type to properly convert sai_attribute to sai_thrift_attribute, and this is manually created file, not sure if any other things could be used in the future in rpc frontend

currently im compiling saimetadata into libsai.so to make it link correctly, but if it's planned to use other libsai than generated from DASH, then we can update SAI/SAI/test/saithriftv2/Makefile to store those metadata objects in that librpcserver.a archive

**Comment by kcudnik** [comment]
since many different parties are using or will use some part of saimetadata, i propose to make libsaimetadata.so and share it everywhere instead to linking objects in each project, deal later with duplicate references, and make size increase of each file, libsaimetadata.so can be already generated by SAI repo latest commit :)

please take a look at further improvements: https://github.com/sonic-net/DASH/pull/432

**Pull request merged**
