### PR TITLE
[sai-gen] Update Sai attribute doc to include the latest support values, also split it into SaiVal and SaiTable for better clarity.

### PR DESCRIPTION
**Pull request by r12f**
No changes to generated contents as below, using the latest main as baseline:

```bash
r12f@r12f-dl380:~/data/code/sonic/DASH/dash-pipeline
$ diff SAI/SAI/inc ~/data/code/sonic/DASH-exp/dash-pipeline/SAI/SAI/inc 

r12f@r12f-dl380:~/data/code/sonic/DASH/dash-pipeline
$ diff SAI/SAI/experimental/ ~/data/code/sonic/DASH-exp/dash-pipeline/SAI/SAI/experimental/

r12f@r12f-dl380:~/data/code/sonic/DASH/dash-pipeline
$ diff SAI/lib ~/data/code/sonic/DASH-exp/dash-pipeline/SAI/lib 
```

### CODE REVIEW

**Comment by r12f** [comment]
ok, as promised in #473 . getting the doc and existing code up to date first.

**Comment by r12f** [comment]
PR is ready to review.

**Review by chrispsommers — APPROVED** [review]
LGTM, thanks!

**Comment by r12f** [comment]
Woot! Thanks!

**Pull request merged**
