### PR TITLE
Add ability to provide @validonly tag

### PR DESCRIPTION
**Pull request by marian-pritsak**

### CODE REVIEW

**Comment by marian-pritsak** [comment]
Need @r12f to approve

**Review by r12f — APPROVED** [review]
LGTM! Thanks Marian!

**Comment by KrisNey-MSFT** [comment]
This is for outer packet.  In Azure there is an option to permit a Cx to set DSCP for VNET.  This should not affect this PR, however want to be cognizant to remember this.

**Comment by KrisNey-MSFT** [comment]
This is outer packet.  We should remember that in Azure we do have scenarios where we permit a Cx to set DSCP in VNET.

**Pull request merged**
