### PR TITLE
SAI Challenger docs & tutorial test-cases

### PR DESCRIPTION
**Pull request by chrispsommers**
- README describing SAI Challenger testbed
- New SAI Challenger tutorials directory and test-cases which run in CI
- Update Makefile and script to ensure ALL tests under test-cases/scale/saic are run, not just vnet
- Add missing dependency trigger in CI .yml file
- Update/refresh some older Test docs

### CODE REVIEW

**Comment by mhanif** [comment]
Hi @chrispsommers, as part of this PR, you may want to update the test/docs/dash-test-sai-challenger.md file as well.  It has some outdated information.  For example, to prepare a repository, it suggests the following:
```
git clone https://github.com/PLVision/DASH.git
cd DASH && git checkout test-framework-extension
```
Which, I believe, shouldn't be there.  The code has been merged and this needs to be updated.

Not sure if you plan to delete/replace this file with some other documentations?  Thanks

**Comment by chrispsommers** [comment]
> Hi @chrispsommers, as part of this PR, you may want to update the test/docs/dash-test-sai-challenger.md file as well. It has some outdated information. For example, to prepare a repository, it suggests the following:
> 
> ```
> git clone https://github.com/PLVision/DASH.git
> cd DASH && git checkout test-framework-extension
> ```
> 
> Which, I believe, shouldn't be there. The code has been merged and this needs to be updated.
> 
> Not sure if you plan to delete/replace this file with some other documentations? Thanks

Hi Hanif,
Thanks for reviewing. You are correct, this file is actually obsolete. I'd considered deleting it but was hesitating because there might be a few useful nuggets which could be moved to a workflows file. I think for now I'll delete it and refresh the workflow files as a follow-on task. I'll make an issue for that so as not to hold this PR up.

**Review by aputriax — APPROVED** [review]

**Comment by KrisNey-MSFT** [comment]
@xumia can you help us with the new Easy CLA check that was added ( and now not passing) please?

**Pull request merged**
