### PR TITLE
Updated SAI-Challenger to latest main as of May 30

### PR DESCRIPTION
**Pull request by andriy-kokhan**
This new version of SAI-Challenger auto-generates `sai_thrift_metadata.py` in run-time.
Fixes Issue https://github.com/sonic-net/DASH/issues/374

### CODE REVIEW

**Comment by chrispsommers** [comment]
Hi @andriy-kokhan thanks for this. If this gets merged, would this allow @vijasrin to re-enable some of the tests which are skipped in https://github.com/sonic-net/DASH/pull/365 (except ones requiring changes to dpugen)?

**Review by chrispsommers — APPROVED** [review]
LGTM, thanks.

**Comment by andriy-kokhan** [comment]
> Hi @andriy-kokhan thanks for this. If this gets merged, would this allow @vijasrin to re-enable some of the tests which are skipped in PR #365 (except ones requiring changes to dpugen)?

This PR enables metadata autogen. But one more improvement is needed - SaiObjType autogen which is addressed in https://github.com/sonic-net/DASH/pull/381.  With these two, some of the tests can be re-enabled. To do that, we will probably make another PR into #365.

**Comment by chrispsommers** [comment]
Thanks for the clarification.

**Pull request merged**
