### PR TITLE
SAI bulk add/remove implementation

### PR DESCRIPTION
**Pull request by marian-pritsak**
Signed-off-by: Marian Pritsak <marianp@mellanox.com>

### CODE REVIEW

**Comment by marian-pritsak** [comment]
Needs a unit test before converting from draft

**Comment by chrispsommers** [comment]
LGTM, but I'll wait for some tests and try them out myself.

**Comment by chrispsommers** [comment]
H @marian-pritsak any chance we can get a unit test or two to validate this and accept it?

**Comment by KrisNey-MSFT** [comment]
@marian-pritsak 
Waiting for test cases as part of this PR

**Comment by chrispsommers** [comment]
@vmytnykx pointed out that the saithrift codegen (in SAI repo) lacks bulk support so it's unlikely we can use these bulk APIs in any saithrift tests in the near term.

@chrispsommers pointed out we could write tests in c++ e.g. under [tests/libsai](https://github.com/sonic-net/DASH/tree/main/dash-pipeline/tests/libsai). He also said the risk was low to accept w/o a test case so we can merge and handle any surprises later. Consensus seemed to be to merge it and move on.

**Review by chrispsommers — APPROVED** [review]

**Comment by chrispsommers** [comment]
Hi @marian-pritsak we've agreed to merge but there is a "status" issue. I don't understand it.

**Comment by KrisNey-MSFT** [comment]
Git command 'amend' and git push force - rinse and repeat?  Vincent has seen this before...
git commit-- amend

**Comment by KrisNey-MSFT** [comment]
@marian-pritsak to update tomorrow 3/30/2023

**Pull request merged**
