### PR TITLE
Fix Broken Link in Documentation for PINS

### PR DESCRIPTION
**Pull request by Aevyz**
Link was missing the https at the front.

### CODE REVIEW

**Comment by KrisNey-MSFT** [comment]
Looks like we need to have the EasyCLA signed @Aevyz (please), then I can Merge :)

**Comment by Aevyz** [comment]
@KrisNey-MSFT Done. Sorry for the delay!

**Comment by r12f** [comment]
thanks @Aevyz !

**Comment by KrisNey-MSFT** [comment]
Thank you so much!  Appreciate the contribution 😊

**Pull request merged**
