### PR TITLE
[doc] Update configuration example for "DASH_ROUTE_TABLE" entries with action "direct"

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
- "vnet" is not needed when the action "direct" is configured.

### CODE REVIEW

**Comment by oleksandrivantsiv** [comment]
Hi @KrisNey-MSFT,

Can you please help to resolve the spellchecker issue? It complains about my last name.

Thanks,
Oleksandr

**Comment by KrisNey-MSFT** [comment]
Hello!  You likely need to add it to the wordlist.txt to resolve the issue; it's located on the main DASH page https://github.com/sonic-net/DASH, just scroll down a bit.  I've edited the wordlist.txt as part of my PR (when I've had one) and it worked for me...

Want to give it a try?

[A screen shot of a computer  Description automatically generated with low confidence]

**Comment by oleksandrivantsiv** [comment]
Thanks, @KrisNey-MSFT! This helped

**Review by svshah-intel — APPROVED** [review]

**Review by reshmaintel — APPROVED** [review]

**Comment by oleksandrivantsiv** [comment]
@chrispsommers done

**Pull request merged**
