### PR TITLE
[dash-sai] Fix buffer and dtel

### PR DESCRIPTION
**Pull request by kcudnik**
Fix api query for buffer and dtel

### CODE REVIEW

**Review by Pterosaur — APPROVED** [review]
LGTM

**Comment by Pterosaur** [comment]
Hi @r12f , I confirmed this PR is good. Could you please help to review and merge it?

**Comment by KrisNey-MSFT** [comment]
Added @r12f as a Reviewer

**Review by r12f — APPROVED** [review]
lgtm too！

**Review by chrispsommers — COMMENTED** [review]
LGTM

**Pull request merged**
